[build]
  base = "frontend/"
  command = "yarn build"
  publish = "build/"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://portfolio-huw1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://portfolio-huw1.onrender.com"

[context.preview.environment]
  REACT_APP_BACKEND_URL = "https://portfolio-huw1.onrender.com"

# Headers pour sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"