services:
  - type: web
    name: lucas-portfolio-backend
    runtime: python3
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    buildCommand: "pip install -r backend/requirements.txt"
    rootDir: backend
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: portfolio_prod
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://lucas-portfolio.netlify.app,https://lcsmrct.netlify.app"
    healthCheckPath: /api/
    
# Configuration pour une base de données PostgreSQL si nécessaire
# databases:
#   - name: portfolio-db
#     databaseName: portfolio
#     user: lucas